<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tipe_kamera_model extends CI_Model
{

    public $table = 'tbl_tipe_kamera';
    public $id = 'id_tipe_kamera';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_tipe_kamera,nama_kamera,nama_tipe_kamera,tbl_tipe_kamera.warna as kode_warna,tbl_tipe_kamera.update_time as update_at');
        $this->datatables->from('tbl_tipe_kamera');
        //add this line for join
        $this->datatables->join('tbl_kamera', 'tbl_tipe_kamera.id_kamera = tbl_kamera.id_kamera');
         $this->datatables->add_column('tipe_warna', anchor(site_url('Tipe_kamera'),'<button class="btn btn-lg" style="background-color: $1;width: 30%; height: 10%;"></button>'), 'kode_warna');

        $this->datatables->add_column('action', anchor(site_url('tipe_kamera/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('tipe_kamera/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('tipe_kamera/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_tipe_kamera');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->datatables->select('id_tipe_kamera,tbl_tipe_kamera.id_kamera,nama_kamera,nama_tipe_kamera,tbl_tipe_kamera.warna as tipe_warna,tbl_tipe_kamera.update_time as update_at');
        $this->datatables->join('tbl_kamera', 'tbl_tipe_kamera.id_kamera = tbl_kamera.id_kamera');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_tipe_kamera', $q);
	$this->db->or_like('id_kamera', $q);
    $this->db->or_like('nama_tipe_kamera', $q);
	$this->db->or_like('warna', $q);
	$this->db->or_like('update_time', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_tipe_kamera', $q);
	$this->db->or_like('id_kamera', $q);
    $this->db->or_like('nama_tipe_kamera', $q);
	$this->db->or_like('warna', $q);
	$this->db->or_like('update_time', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tipe_kamera_model.php */
/* Location: ./application/models/Tipe_kamera_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-18 05:05:50 */
/* http://harviacode.com */